version: "3.3"

services:
  traefik:
    image: traefik:v2.1
    networks:
      - traefik
    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_HTTPS_PORT}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LETSENCRYPT_FOLDER}:/letsencrypt
    command:
      - --api.insecure=false
      - --api.dashboard=true
      - --log.level=ERROR
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=traefik
      - --entrypoints.http.address=:${TRAEFIK_HTTP_PORT}
      - --entrypoints.https.address=:${TRAEFIK_HTTPS_PORT}
      - --certificatesResolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesResolvers.letsencrypt.acme.tlsChallenge=true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.http-to-https-redirect.rule=hostregexp(`{host:[a-z-.]+}`)
        - traefik.http.routers.http-to-https-redirect.entrypoints=http
        - traefik.http.routers.http-to-https-redirect.middlewares=http-to-https-redirect
        - traefik.http.middlewares.http-to-https-redirect.redirectscheme.scheme=https
        - traefik.http.routers.api.rule=Host(`${TRAEFIK_API_DOMAIN}`)
        - traefik.http.routers.api.service=api@internal
        - traefik.http.routers.api.entryPoints=https
        - traefik.http.routers.api.tls=true
        - traefik.http.routers.api.tls.certresolver=letsencrypt
        - traefik.http.services.api.loadbalancer.server.port=8080

networks:
  traefik:
    external: true
