version: "3.3"

services:
  traefik:
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.api.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN}`)
        - traefik.http.services.api.loadbalancer.server.port=${TRAEFIK_DASHBOARD_PORT}
