version: "3.3"

services:
  traefik:
    image: traefik:v2.1
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN}`)
      - traefik.http.services.api.loadbalancer.server.port=${TRAEFIK_DASHBOARD_PORT}
    networks:
      - traefik
    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_HTTPS_PORT}:443
      - ${TRAEFIK_DASHBOARD_PORT}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik:
    external: true
